spring:
    application:
        name: auth
    
    config:
        import: file:src\main\resources\env.properties

    datasource:
        url: jdbc:mysql://localhost:3306/${DB_DATABASE}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

server:
    port: 8080

jwt:
    token:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 120000
        refresh-expiration: 300000
    
    cors:
        allowed-origins:
            - "http://localhost:${server.port}"
        allowed-methods: 
            - GET
            - POST
        allowed-headers: 
            - Authorization
            - Content-Type