spring:
    application:
        name: auth
    
    config:
        import: file:src\main\resources\env.properties
    
    mvc:
        view:
            suffix: .html

    datasource:
        url: jdbc:mysql://localhost:3306/${DB_DATABASE}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
    
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    
    data:
        redis:
            host: localhost
            port: 6379

server:
    port: 8080

auth:
    base-url: http://localhost:${server.port}
    token:
        secret-key: ${JWT_SECRET_KEY}
        jwt-expiration: 10800000
        refresh-expiration: 604800000
        token-expiration: 3600000
    
    cors:
        allowed-origins:
            - "http://localhost:${server.port}"
        allowed-methods: 
            - GET
            - POST
        allowed-headers: 
            - Authorization
            - Content-Type