spring:
    application:
        name: auth

    datasource:
        url: jdbc:mysql://localhost:3306/portfoliopro
        username: root
        password: Arbs24022001@
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

server:
    port: 8080

jwt:
    token:
        # todo: make it encrypted
        secret-key: "d5579bf7a834d54c889b60f5ba005c2551505c20128897997612e0c61a84e4b3"
        expiration: 3600000
    
    cors:
        allowed-origins:
            - "http://localhost:${server.port}"
        allowed-methods: 
            - GET
            - POST
        allowed-headers: 
            - Authorization
            - Content-Type